# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lbcqc.github.io/
date_format: "ordinal"
title: lbcqc
subtitle: "lbcqc gogogo"
description: "个人博客"
keywords: shl
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Shuai Li
organization: sundray
organization_url: http://www.sundray.com
github_username: lbcqc
location: HaiNan, China
email: shuaili7194@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: lbcqc/lbcqc.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: mzlogin
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    enable: true #是否开启
    githubID: lbcqc #你的Github用户名
    repo: blog-comments #Github仓库名称
    owner: lbcqc
    adminUser: moshiyeap # 评论初始化账户(GitHub ID)
    distractionFreeMode: true # 是否开启分心自由模式 也就是免打扰
    clientID: 30d1ecab8575bf1ab9d4
    clientSecret: ecca20f7471854e677a2ff25e0ca61d1e34d3547
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
